import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Download, Printer, ShieldCheck } from 'lucide-react';
import { api } from '../api/client';
import { usePolling } from '../hooks/usePolling';
import { ErrorState, LoadingState } from '../components/ui';
import { humanize } from '../lib/format';
import {
  buildReportView, fmtDateTime, fmtDuration, fmtMetric, fmtTime, NA, pctText, severityLabel,
} from '../lib/reportModel';
import type { ReportContent, ReportMetricStatus } from '../types';

export default function ReportDetailsPage() {
  const { id } = useParams();
  const report = usePolling(() => api.report(Number(id)), 0, [id]);

  if (report.loading) return <LoadingState label="Loading report…" />;
  if (report.error || !report.data) return <ErrorState message={report.error ?? 'Not found'} onRetry={report.refetch} />;

  const c = report.data.content;
  const v = buildReportView(c);
  const reportId = `RPT-${String(report.data.id).padStart(5, '0')}`;
  const invId = v.investigationId ?? report.data.investigation_id;
  const title = deriveTitle(c);

  return (
    <div className="report-viewer">
      {/* ---- Viewer toolbar (never printed) ---- */}
      <div className="no-print sticky top-0 z-10 -mx-4 mb-6 flex flex-wrap items-center justify-between gap-3 border-b border-space-700 bg-space-900/90 px-4 py-3 backdrop-blur sm:-mx-6 sm:px-6">
        <div className="flex items-center gap-3">
          <Link to="/reports" className="inline-flex items-center gap-1.5 rounded-lg border border-space-700 px-3 py-1.5 text-sm text-slate-300 hover:bg-space-800">
            <ArrowLeft className="h-4 w-4" /> Back
          </Link>
          <div className="text-xs text-slate-500">
            <span className="text-slate-400">{reportId}</span> · Investigation #{invId}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => window.print()} className="inline-flex items-center gap-1.5 rounded-lg border border-space-700 px-3 py-1.5 text-sm text-slate-200 hover:bg-space-800">
            <Printer className="h-4 w-4" /> Print
          </button>
          <button onClick={() => window.print()} className="inline-flex items-center gap-1.5 rounded-lg bg-accent-orange px-3.5 py-1.5 text-sm font-semibold text-white hover:bg-orange-500">
            <Download className="h-4 w-4" /> Export PDF
          </button>
        </div>
      </div>

      {/* ---- The professional document ---- */}
      <div className="report-print-root mx-auto w-full max-w-[880px]">
        <article className="report-doc">
          {/* Cover / header */}
          <header className="report-section report-cover">
            <div className="report-cover-top">
              <div>
                <div className="report-brand">PROJECT ORION</div>
                <div className="report-brand-sub">Mission Intelligence Platform</div>
              </div>
              <SeverityBadge severity={v.rca.severity ?? c.severity} />
            </div>
            <div className="report-kicker">MISSION INVESTIGATION REPORT</div>
            <h1 className="report-title">{title.line1}</h1>
            {title.line2 && <div className="report-title-sub">{title.line2}</div>}

            <dl className="report-cover-meta">
              <Meta k="Report ID" val={reportId} />
              <Meta k="Investigation ID" val={`#${invId}`} />
              <Meta k="Satellite" val={c.satellite.name} />
              <Meta k="Mission" val={c.satellite.mission} />
              <Meta k="Orbit" val={c.satellite.orbit_type} />
              <Meta k="NORAD ID" val={c.satellite.norad_id} />
              <Meta k="Generated At" val={fmtDateTime(c.generated_at)} />
              <Meta k="Generated By" val="ORION Report Generation Agent" />
              <Meta k="Classification" val={v.classification} />
              <Meta k="Report Status" val={v.reportStatus} />
            </dl>

            <div className="report-disclaimer">
              <ShieldCheck className="h-4 w-4 flex-shrink-0" />
              <span>
                Project ORION is a simulation and decision-support platform. All recommendations are advisory and
                require authorized human review.
              </span>
            </div>
          </header>

          {/* Executive summary */}
          <Section title="Executive Summary">
            <div className="report-kpis">
              <Kpi label="Severity" value={severityLabel(v.rca.severity ?? c.severity)} tone={sevTone(v.rca.severity ?? c.severity)} />
              <Kpi label="RCA Confidence" value={pctText(v.rca.confidence ?? c.confidence)} tone="neutral" />
              <Kpi label="Anomalies Detected" value={String(v.anomalies.length)} tone="neutral" />
              <Kpi label="Satellite Health" value={v.satelliteHealth != null ? `${v.satelliteHealth.toFixed(2)} / 100` : NA} tone={healthTone(v.satelliteHealth)} />
            </div>
            <dl className="report-kv">
              <KV k="Primary Finding" val={v.executive.primary_finding} />
              <KV k="Detected Condition" val={v.executive.detected_condition} />
              <KV k="Operational Impact" val={v.executive.operational_impact} />
              <KV k="Current Status" val={v.executive.current_status} />
              <KV k="Required Human Action" val={v.executive.required_human_action} highlight />
            </dl>
          </Section>

          {/* Incident overview */}
          <Section title="Incident Overview">
            <dl className="report-kv report-kv-2col">
              <KV k="Investigation ID" val={`#${invId}`} />
              <KV k="Investigation Status" val={v.executive.current_status} />
              <KV k="Satellite" val={`${c.satellite.name} (${c.satellite.id})`} />
              <KV k="Mission" val={c.satellite.mission} />
              <KV k="Orbit" val={c.satellite.orbit_type} />
              <KV k="NORAD ID" val={c.satellite.norad_id} />
              <KV k="Detection Time" val={fmtDateTime(v.detectionTime)} />
              <KV k="Investigation Start" val={fmtDateTime(v.startedAt ?? c.generated_at)} />
              <KV k="Investigation Completion" val={fmtDateTime(v.completedAt)} />
              <KV k="Total Anomalies" val={String(v.anomalies.length)} />
              <KV k="Highest Severity" val={severityLabel(v.rca.severity ?? c.severity)} />
              <KV k="RCA Confidence" val={pctText(v.rca.confidence ?? c.confidence)} />
              <KV k="Current Satellite Health" val={v.satelliteHealth != null ? `${v.satelliteHealth.toFixed(2)} / 100` : NA} />
            </dl>
          </Section>

          {/* Telemetry snapshot */}
          <Section title="Satellite Telemetry Snapshot" subtitle={v.telemetryTime ? `Observed ${fmtDateTime(v.telemetryTime)}` : undefined}>
            {v.telemetry.length === 0 ? (
              <NotAvailable message="No telemetry snapshot is available for this investigation." />
            ) : (
              <table className="report-table">
                <thead>
                  <tr><th>Metric</th><th>Observed</th><th>Expected / Threshold</th><th>Status</th></tr>
                </thead>
                <tbody>
                  {v.telemetry.map((m) => (
                    <tr key={m.key}>
                      <td className="font-medium">{m.label}</td>
                      <td className="tabular">{fmtMetric(m.value, m.unit)}</td>
                      <td>{m.expected ?? '—'}</td>
                      <td><MetricPill status={m.status} /></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </Section>

          {/* Detected anomalies */}
          <Section title="Detected Anomalies">
            {v.anomalies.length === 0 ? (
              <NotAvailable message="No anomalies were recorded for this investigation." />
            ) : (
              <table className="report-table">
                <thead>
                  <tr><th>#</th><th>Anomaly Type</th><th>Metric</th><th>Observed</th><th>Expected</th><th>Severity</th><th>Detected</th><th>Status</th></tr>
                </thead>
                <tbody>
                  {v.anomalies.map((a) => (
                    <tr key={a.index}>
                      <td className="tabular">{a.index}</td>
                      <td className="font-medium">{a.anomaly_type}</td>
                      <td>{a.metric}</td>
                      <td className="tabular">{a.observed_value}</td>
                      <td>{a.expected}</td>
                      <td><SeverityInline sev={a.severity} /></td>
                      <td className="tabular whitespace-nowrap">{a.detection_time ? fmtTime(a.detection_time) : '—'}</td>
                      <td>{humanize(a.status)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
            {v.anomalies.some((a) => a.evidence) && (
              <ul className="report-evidence-notes">
                {v.anomalies.filter((a) => a.evidence).map((a) => (
                  <li key={a.index}><b>{a.anomaly_type}:</b> {a.evidence}</li>
                ))}
              </ul>
            )}
          </Section>

          {/* Root cause analysis */}
          <Section title="Root Cause Analysis" pageBreak>
            <div className="report-rca-head">
              <div>
                <div className="report-label">Primary Root Cause</div>
                <div className="report-rca-cause">{v.rca.primary_root_cause ? humanize(v.rca.primary_root_cause) : 'Inconclusive'}</div>
              </div>
              <div className="report-rca-metrics">
                <MiniStat label="Confidence" value={pctText(v.rca.confidence)} />
                <MiniStat label="Severity" value={severityLabel(v.rca.severity)} tone={sevTone(v.rca.severity)} />
                <MiniStat label="Analysis Status" value={v.rca.status} />
              </div>
            </div>

            <SubHead>Reasoning Summary</SubHead>
            {v.rca.reasoning.length ? (
              <ul className="report-bullets">{v.rca.reasoning.map((r, i) => <li key={i}>{r}</li>)}</ul>
            ) : <NotAvailable message="No reasoning summary available." />}

            <SubHead>Contributing Factors</SubHead>
            {v.rca.contributing_factors.length ? (
              <div className="report-bars">
                {v.rca.contributing_factors.map((f, i) => (
                  <Bar key={i} label={f.factor} value={f.weight} />
                ))}
              </div>
            ) : <NotAvailable message="No contributing factors recorded." />}

            {v.rca.evidence_distribution.length > 0 && (
              <>
                <SubHead>Evidence Distribution</SubHead>
                <div className="report-bars">
                  {v.rca.evidence_distribution.map((d, i) => (
                    <Bar key={i} label={d.root_cause} value={d.normalized} accent={d.root_cause === humanize(v.rca.primary_root_cause ?? '')} />
                  ))}
                </div>
              </>
            )}

            <SubHead>Supporting Evidence</SubHead>
            {v.rca.supporting_evidence.length ? (
              <table className="report-table">
                <thead><tr><th>Evidence ID</th><th>Type</th><th>Source</th><th>Observation</th><th>Weight</th><th>Time</th></tr></thead>
                <tbody>
                  {v.rca.supporting_evidence.map((e) => (
                    <tr key={e.id}>
                      <td className="tabular">{e.id}</td>
                      <td>{e.type}</td>
                      <td>{e.source}</td>
                      <td>{e.observation}</td>
                      <td className="tabular">{e.weight.toFixed(2)}</td>
                      <td className="tabular whitespace-nowrap">{fmtTime(e.timestamp)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : <NotAvailable message="Structured supporting-evidence records are not available for this report." />}

            {v.rca.alternative_hypotheses.length > 0 && (
              <>
                <SubHead>Alternative Hypotheses</SubHead>
                <table className="report-table">
                  <thead><tr><th>Hypothesis</th><th>Confidence</th><th>Assessment</th></tr></thead>
                  <tbody>
                    {v.rca.alternative_hypotheses.map((h, i) => (
                      <tr key={i}>
                        <td className="font-medium">{h.hypothesis}</td>
                        <td className="tabular">{pctText(h.confidence)}</td>
                        <td>{h.note}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </>
            )}
          </Section>

          {/* Investigation timeline */}
          <Section title="Investigation Timeline">
            {c.timeline.length ? (
              <ol className="report-timeline">
                {c.timeline.map((t, i) => (
                  <li key={i}>
                    <span className="report-timeline-time tabular">{fmtTime(t.time)}</span>
                    <span className="report-timeline-dot" />
                    <span className="report-timeline-event">{t.event}</span>
                  </li>
                ))}
              </ol>
            ) : <NotAvailable message="No timeline events recorded." />}
          </Section>

          {/* Agent execution summary */}
          <Section title="AI Agent Execution Summary" pageBreak>
            {v.agents.length ? (
              <table className="report-table">
                <thead><tr><th>Agent</th><th>Purpose</th><th>Status</th><th>Started</th><th>Completed</th><th>Duration</th><th>Confidence</th></tr></thead>
                <tbody>
                  {v.agents.map((a, i) => (
                    <tr key={i}>
                      <td className="font-medium">{a.agent_name}</td>
                      <td>{a.purpose}</td>
                      <td><AgentStatusPill status={a.status} /></td>
                      <td className="tabular whitespace-nowrap">{a.started_at ? fmtTime(a.started_at) : '—'}</td>
                      <td className="tabular whitespace-nowrap">{a.completed_at ? fmtTime(a.completed_at) : '—'}</td>
                      <td className="tabular">{fmtDuration(a.duration_ms)}</td>
                      <td className="tabular">{a.confidence != null ? pctText(a.confidence) : '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : <NotAvailable message="No agent execution records available." />}
          </Section>

          {/* Evidence & decision traceability */}
          <Section title="Evidence & Decision Traceability">
            {v.rca.supporting_evidence.length > 0 && (
              <table className="report-table">
                <thead><tr><th>Evidence ID</th><th>Source</th><th>Observation</th><th>Weight</th><th>Used in Decision</th><th>Time</th></tr></thead>
                <tbody>
                  {v.rca.supporting_evidence.map((e) => (
                    <tr key={e.id}>
                      <td className="tabular">{e.id}</td>
                      <td>{e.source}</td>
                      <td>{e.observation}</td>
                      <td className="tabular">{e.weight.toFixed(2)}</td>
                      <td>{e.supports ? 'Yes' : 'No'}</td>
                      <td className="tabular whitespace-nowrap">{fmtTime(e.timestamp)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
            <SubHead>Decision Trace</SubHead>
            <div className="report-trace">
              {v.decisionTrace.map((step, i) => (
                <span key={i} className="report-trace-step">
                  {step}{i < v.decisionTrace.length - 1 && <span className="report-trace-arrow">→</span>}
                </span>
              ))}
            </div>
          </Section>

          {/* Recommendations */}
          <Section title="Recommendations">
            {c.recommendations.length ? (
              <div className="report-recs">
                {c.recommendations.map((r, i) => (
                  <div key={i} className="report-rec">
                    <PriorityBadge priority={r.priority} />
                    <div className="report-rec-body">
                      <div className="report-rec-action">{r.action}</div>
                      <div className="report-rec-reason">{r.rationale}</div>
                      <div className="report-rec-meta">
                        <span>Responsible: <b>Mission Director</b></span>
                        <span>Human Approval Required: <b>Yes</b></span>
                        <span>Status: <b>Advisory — Pending Review</b></span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : <NotAvailable message="No recommendations recorded." />}
            <p className="report-note">Project ORION is decision-support only. Recommendations are advisory; no autonomous or corrective action is executed by the platform.</p>
          </Section>

          {/* Risk assessment */}
          <Section title="Risk Assessment">
            {v.risk.length ? (
              <table className="report-table">
                <thead><tr><th>Risk Category</th><th>Likelihood</th><th>Impact</th><th>Risk Level</th><th>Recommended Review</th></tr></thead>
                <tbody>
                  {v.risk.map((r, i) => (
                    <tr key={i}>
                      <td className="font-medium">{r.category}</td>
                      <td>{r.likelihood}</td>
                      <td>{r.impact}</td>
                      <td><RiskPill level={r.level} /></td>
                      <td>{r.mitigation}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : <NotAvailable message="Insufficient likelihood/impact data to compute a risk assessment." />}
          </Section>

          {/* Audit trail */}
          <Section title="Audit Trail" pageBreak>
            {v.audit.length ? (
              <table className="report-table">
                <thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Resource</th><th>Result</th></tr></thead>
                <tbody>
                  {v.audit.map((r, i) => (
                    <tr key={i}>
                      <td className="tabular whitespace-nowrap">{fmtDateTime(r.timestamp)}</td>
                      <td>{r.actor}</td>
                      <td>{r.action}</td>
                      <td>{r.resource}</td>
                      <td>{humanize(r.result)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : <NotAvailable message="No audit trail data available for this investigation." />}
          </Section>

          {/* System & model transparency */}
          <Section title="System & Model Transparency">
            <dl className="report-kv report-kv-2col">
              <KV k="Analysis Mode" val={v.transparency?.analysis_mode ?? 'DETERMINISTIC'} />
              <KV k="RCA Engine Version" val={v.transparency?.rca_engine_version ?? NA} />
              <KV k="Ruleset Version" val={v.transparency?.ruleset_version ?? NA} />
              <KV k="Report Generator Version" val={v.transparency?.report_generator_version ?? NA} />
              <KV k="LLM Provider" val={v.transparency?.llm_provider ?? 'none'} />
              <KV k="LLM Model" val={v.transparency?.llm_model ?? NA} />
              <KV k="Fallback Mode Used" val={v.transparency ? (v.transparency.fallback_mode_used ? 'Yes' : 'No') : NA} />
              <KV k="Grounding Status" val={v.transparency?.grounding_status ?? 'DETERMINISTIC_RULES'} />
              <KV k="Human Review Required" val="Yes" />
            </dl>
          </Section>

          {/* Report quality / completeness */}
          <Section title="Report Quality & Completeness">
            <div className="report-score">
              <div className="report-score-value">{v.completeness.score}<span className="report-score-max"> / 100</span></div>
              <div className="report-score-label">REPORT COMPLETENESS SCORE</div>
            </div>
            <div className="report-bars">
              {v.completeness.categories.map((cat) => (
                <Bar key={cat.key} label={cat.label} value={cat.score / cat.max} suffix={`${cat.score}/${cat.max}`} />
              ))}
            </div>
          </Section>

          {/* Approval & human review */}
          <Section title="Approval & Human Review">
            <dl className="report-kv report-kv-2col">
              <KV k="Review Status" val={v.review.status} highlight />
              <KV k="Reviewed By" val={v.review.reviewed_by} />
              <KV k="Review Date" val={fmtDateTime(v.review.review_date)} />
              <KV k="Decision" val={v.review.decision} />
              <KV k="Reviewer Notes" val={v.review.notes} />
            </dl>
            <p className="report-note">No operational action has been executed by Project ORION. All recommendations require authorized human review.</p>
          </Section>

          {/* References + provenance (retained, audit-useful) */}
          {(c.references.length > 0 || c.provenance.length > 0) && (
            <Section title="References & Data Provenance">
              {c.references.length > 0 && (
                <ul className="report-refs">
                  {c.references.map((r, i) => (
                    <li key={i}>{r.title} <span className="report-muted">— {r.host_venue}, {r.publication_year}</span></li>
                  ))}
                </ul>
              )}
              {c.provenance.length > 0 && (
                <table className="report-table">
                  <thead><tr><th>Source</th><th>Reference</th><th>Mode</th></tr></thead>
                  <tbody>
                    {c.provenance.map((p, i) => (
                      <tr key={i}>
                        <td>{p.source_name}</td>
                        <td className="report-muted break-all">{p.source_url || '—'}</td>
                        <td>{p.mode}{p.fallback_used ? ' (fallback)' : ''}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </Section>
          )}

          <div className="report-safety">
            <ShieldCheck className="h-4 w-4 flex-shrink-0" />
            <span>{c.safety_statement}</span>
          </div>
        </article>

        {/* Print-only running footer */}
        <div className="report-footer" aria-hidden="true">
          <span>PROJECT ORION · Simulation / Decision-Support Only</span>
          <span>CONFIDENTIAL — INTERNAL USE · {reportId}</span>
        </div>
      </div>
    </div>
  );
}

// ---------- Title derivation ----------
function deriveTitle(c: ReportContent): { line1: string; line2?: string } {
  const cause = c.root_cause ? humanize(c.root_cause).toUpperCase() : 'ANOMALY';
  return { line1: `${c.satellite.id} — ${cause}`, line2: `${c.satellite.mission} · Investigation` };
}

// ---------- Presentational subcomponents ----------

function Section({ title, subtitle, children, pageBreak }: { title: string; subtitle?: string; children: React.ReactNode; pageBreak?: boolean }) {
  return (
    <section className={`report-section${pageBreak ? ' report-page-break' : ''}`}>
      <div className="report-section-head">
        <h2 className="report-section-title">{title}</h2>
        {subtitle && <span className="report-section-sub">{subtitle}</span>}
      </div>
      {children}
    </section>
  );
}

function SubHead({ children }: { children: React.ReactNode }) {
  return <h3 className="report-subhead">{children}</h3>;
}

function Meta({ k, val }: { k: string; val: string }) {
  return (
    <div className="report-meta-item">
      <dt>{k}</dt>
      <dd>{val || NA}</dd>
    </div>
  );
}

function KV({ k, val, highlight }: { k: string; val: string; highlight?: boolean }) {
  return (
    <div className={`report-kv-row${highlight ? ' report-kv-highlight' : ''}`}>
      <dt>{k}</dt>
      <dd>{val || NA}</dd>
    </div>
  );
}

type Tone = 'critical' | 'high' | 'medium' | 'good' | 'neutral';

function Kpi({ label, value, tone }: { label: string; value: string; tone: Tone }) {
  return (
    <div className={`report-kpi report-kpi-${tone}`}>
      <div className="report-kpi-label">{label}</div>
      <div className="report-kpi-value">{value}</div>
    </div>
  );
}

function MiniStat({ label, value, tone }: { label: string; value: string; tone?: Tone }) {
  return (
    <div className="report-ministat">
      <div className="report-label">{label}</div>
      <div className={`report-ministat-value${tone ? ` report-text-${tone}` : ''}`}>{value}</div>
    </div>
  );
}

function Bar({ label, value, accent, suffix }: { label: string; value: number; accent?: boolean; suffix?: string }) {
  const pct = Math.max(0, Math.min(100, Math.round(value * 100)));
  return (
    <div className="report-bar-row">
      <span className="report-bar-label">{label}</span>
      <span className="report-bar-track"><span className={`report-bar-fill${accent ? ' report-bar-accent' : ''}`} style={{ width: `${pct}%` }} /></span>
      <span className="report-bar-value tabular">{suffix ?? `${pct}%`}</span>
    </div>
  );
}

function NotAvailable({ message }: { message: string }) {
  return <p className="report-na">{message}</p>;
}

function SeverityBadge({ severity }: { severity: string | null | undefined }) {
  return <span className={`report-sev-badge report-sev-${(severity ?? 'none').toLowerCase()}`}>{severityLabel(severity)}</span>;
}

function SeverityInline({ sev }: { sev: string }) {
  if (!sev || sev === '—') return <span>—</span>;
  return <span className={`report-sev-inline report-sev-${sev.toLowerCase()}`}>{sev}</span>;
}

function MetricPill({ status }: { status: ReportMetricStatus }) {
  return <span className={`report-pill report-pill-${status.toLowerCase()}`}>{status === 'UNKNOWN' ? 'N/A' : status}</span>;
}

function AgentStatusPill({ status }: { status: string }) {
  const cls = status === 'COMPLETED' ? 'good' : status === 'FALLBACK_USED' ? 'medium' : status === 'FAILED' ? 'critical' : 'neutral';
  return <span className={`report-pill report-pill-status-${cls}`}>{humanize(status)}</span>;
}

function RiskPill({ level }: { level: string }) {
  const cls = level === 'HIGH' ? 'critical' : level === 'MEDIUM' ? 'medium' : 'neutral';
  return <span className={`report-pill report-pill-status-${cls}`}>{level}</span>;
}

function PriorityBadge({ priority }: { priority: string }) {
  const p = priority?.toUpperCase();
  const { tag, label, cls } =
    p === 'CRITICAL' ? { tag: 'P1', label: 'IMMEDIATE REVIEW', cls: 'critical' }
    : p === 'HIGH' ? { tag: 'P2', label: 'HIGH PRIORITY', cls: 'high' }
    : p === 'MEDIUM' ? { tag: 'P2', label: 'HIGH PRIORITY', cls: 'medium' }
    : { tag: 'P3', label: 'ROUTINE MONITORING', cls: 'neutral' };
  return (
    <div className={`report-priority report-priority-${cls}`}>
      <span className="report-priority-tag">{tag}</span>
      <span className="report-priority-label">{label}</span>
    </div>
  );
}

// ---------- Tone helpers ----------
function sevTone(sev: string | null | undefined): Tone {
  switch ((sev ?? '').toUpperCase()) {
    case 'CRITICAL': return 'critical';
    case 'HIGH': return 'high';
    case 'MEDIUM': return 'medium';
    case 'LOW': return 'good';
    default: return 'neutral';
  }
}
function healthTone(h: number | null): Tone {
  if (h == null) return 'neutral';
  if (h >= 80) return 'good';
  if (h >= 55) return 'medium';
  return 'critical';
}
