/**
 * Report view-model normalization.
 *
 * The professional Report Viewer renders a single normalized shape. Reports
 * generated by the v2 backend generator already carry every structured section;
 * older reports carry only the legacy fields. This module prefers the structured
 * fields when present and otherwise derives a best-effort equivalent from the
 * legacy content — never fabricating values. Where nothing can be derived, the
 * section is empty and the UI shows "Not Available".
 *
 * It intentionally has NO React/DOM dependency so it is unit-testable.
 */
import { humanize } from './format';
import type {
  ReportAgentDetail,
  ReportAnomalyRow,
  ReportAuditRow,
  ReportCompleteness,
  ReportContent,
  ReportExecutiveSummary,
  ReportRca,
  ReportReview,
  ReportRiskRow,
  ReportSystemTransparency,
  ReportTelemetryMetric,
} from '../types';

export const NA = 'Not Available';

export interface ReportView {
  telemetry: ReportTelemetryMetric[];
  telemetryTime: string | null;
  anomalies: ReportAnomalyRow[];
  rca: ReportRca;
  agents: ReportAgentDetail[];
  decisionTrace: string[];
  risk: ReportRiskRow[];
  audit: ReportAuditRow[];
  transparency: ReportSystemTransparency | null;
  completeness: ReportCompleteness;
  review: ReportReview;
  executive: ReportExecutiveSummary;
  reportStatus: string;
  classification: string;
  investigationId: number | null;
  satelliteHealth: number | null;
  detectionTime: string | null;
  startedAt: string | null;
  completedAt: string | null;
}

// ---------- Formatting ----------

export function fmtDateTime(iso: string | null | undefined): string {
  if (!iso) return NA;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return NA;
  return d.toISOString().slice(0, 19).replace('T', ' ') + ' UTC';
}

export function fmtTime(iso: string | null | undefined): string {
  if (!iso) return '—';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toISOString().slice(11, 19);
}

export function fmtDuration(ms: number | null | undefined): string {
  if (ms == null) return '—';
  if (ms < 1000) return `${ms} ms`;
  return `${(ms / 1000).toFixed(2)} s`;
}

export function fmtMetric(value: number | null, unit: string): string {
  if (value == null || Number.isNaN(value)) return NA;
  const rounded = Math.round(value * 100) / 100;
  return unit === '%' || unit === '°' ? `${rounded}${unit}` : `${rounded} ${unit}`;
}

export function pctText(v: number | null | undefined): string {
  if (v == null) return NA;
  return `${Math.round(v * 100)}%`;
}

/** Human severity label; used for the cover status badge. */
export function severityLabel(sev: string | null | undefined): string {
  return sev ? sev.toUpperCase() : 'UNCLASSIFIED';
}

// ---------- Derivations (fallback for legacy reports) ----------

function deriveExecutive(c: ReportContent): ReportExecutiveSummary {
  if (c.executive_summary) return c.executive_summary;
  const rc = c.root_cause ? humanize(c.root_cause) : 'Inconclusive';
  return {
    primary_finding: c.root_cause
      ? `${rc} identified as the most probable root cause at ${pctText(c.confidence)} confidence.`
      : 'Root cause analysis was inconclusive; further review required.',
    detected_condition: c.detected_anomalies.length ? c.detected_anomalies.map(humanize).join(', ') : NA,
    operational_impact: c.severity ? `Assessed severity ${c.severity}.` : NA,
    current_status: c.resolution || NA,
    required_human_action: c.recommendations[0]?.action ?? 'Authorized Mission Director review of the findings.',
  };
}

function deriveAnomalies(c: ReportContent): ReportAnomalyRow[] {
  if (c.anomalies_detail?.length) return c.anomalies_detail;
  return c.detected_anomalies.map((type, i) => ({
    index: i + 1,
    anomaly_type: humanize(type),
    metric: '—',
    observed_value: NA,
    expected: NA,
    severity: c.severity ?? '—',
    detection_time: null,
    status: '—',
    evidence: null,
  }));
}

function deriveRca(c: ReportContent): ReportRca {
  if (c.rca) return c.rca;
  const scoring = c.scoring_breakdown ?? [];
  const sorted = [...scoring].sort((a, b) => b.normalized - a.normalized);
  const top = sorted.find((s) => s.root_cause === c.root_cause) ?? sorted[0];
  return {
    primary_root_cause: c.root_cause,
    confidence: c.confidence,
    severity: c.severity,
    status: c.root_cause ? 'COMPLETED' : 'INCONCLUSIVE',
    reasoning: (c.explanation ?? '')
      .split(/(?<=[.!?])\s+/)
      .map((s) => s.trim())
      .filter(Boolean)
      .slice(0, 6),
    contributing_factors: (top?.contributions ?? []).map((f) => ({ factor: humanize(f.factor), weight: f.weight })),
    evidence_distribution: sorted.map((s) => ({ root_cause: humanize(s.root_cause), normalized: s.normalized })),
    supporting_evidence: [],
    alternative_hypotheses: sorted
      .filter((s) => s.root_cause !== (c.root_cause ?? top?.root_cause))
      .slice(0, 3)
      .map((s) => ({ hypothesis: humanize(s.root_cause), confidence: s.normalized, note: 'Lower composite evidence score.' })),
  };
}

function deriveAgents(c: ReportContent): ReportAgentDetail[] {
  if (c.agents_detail?.length) return c.agents_detail;
  return c.agent_execution_history.map((a) => ({
    agent_id: a.agent_name,
    agent_name: a.agent_name,
    purpose: '—',
    status: a.status,
    started_at: null,
    completed_at: null,
    duration_ms: a.duration_ms,
    output_summary: a.output_summary,
    confidence: null,
  }));
}

function deriveAudit(c: ReportContent): ReportAuditRow[] {
  if (c.audit_trail?.length) return c.audit_trail;
  return c.timeline.map((t) => ({
    timestamp: t.time,
    actor: 'System',
    action: t.event,
    resource: c.satellite.id,
    result: '—',
  }));
}

function deriveReview(c: ReportContent): ReportReview {
  if (c.review) return c.review;
  const decided = c.mission_director_decision && c.mission_director_decision !== 'PENDING';
  return {
    status: decided ? `${c.mission_director_decision} — HUMAN REVIEWED` : 'PENDING HUMAN REVIEW',
    reviewed_by: decided ? 'Mission Director' : 'Not Yet Assigned',
    review_date: c.reviewed_at,
    decision: c.mission_director_decision || 'PENDING',
    notes: '—',
  };
}

/**
 * Deterministic completeness fallback for legacy reports, mirroring the backend
 * formula (see backend reportComposer.computeCompleteness). Category maxima:
 * 20/20/15/15/10/10/10 = 100.
 */
function deriveCompleteness(c: ReportContent): ReportCompleteness {
  if (c.completeness) return c.completeness;
  const clamp = (v: number, max: number) => Math.max(0, Math.min(max, v));
  const s = c.satellite;
  const satMeta = !!(s.name && s.mission && s.orbit_type && s.norad_id);
  const evidenceCount = (c.telemetry_evidence?.length ?? 0) + (c.space_weather_evidence ? 1 : 0) + (c.orbit_evidence ? 1 : 0);
  const data = clamp((satMeta ? 8 : 0) + 4, 20); // no telemetry snapshot in legacy content
  const evidence = clamp((Math.min(evidenceCount, 5) / 5) * 20, 20);
  const rca = clamp((c.confidence ?? 0) * 15, 15);
  const trace = clamp((Math.min(c.agent_execution_history.length, 6) / 6) * 9 + (c.timeline.length ? 3 : 0), 15);
  const audit = clamp((Math.min(c.timeline.length, 5) / 5) * 10, 10);
  const rec = clamp((Math.min(c.recommendations.length, 3) / 3) * 10, 10);
  const integrity = clamp((c.root_cause ? 4 : 0) + (c.severity ? 3 : 0) + (c.safety_statement ? 3 : 0), 10);
  return {
    score: Math.round(data + evidence + rca + trace + audit + rec + integrity),
    max: 100,
    categories: [
      { key: 'data_completeness', label: 'Data Completeness', score: Math.round(data), max: 20 },
      { key: 'evidence_coverage', label: 'Evidence Coverage', score: Math.round(evidence), max: 20 },
      { key: 'rca_confidence', label: 'RCA Confidence', score: Math.round(rca), max: 15 },
      { key: 'traceability', label: 'Traceability', score: Math.round(trace), max: 15 },
      { key: 'auditability', label: 'Auditability', score: Math.round(audit), max: 10 },
      { key: 'recommendation_quality', label: 'Recommendation Quality', score: Math.round(rec), max: 10 },
      { key: 'report_integrity', label: 'Report Integrity', score: Math.round(integrity), max: 10 },
    ],
  };
}

/** Build the fully-normalized view model consumed by the Report Viewer. */
export function buildReportView(c: ReportContent): ReportView {
  return {
    telemetry: c.telemetry_snapshot ?? [],
    telemetryTime: c.telemetry_snapshot_time ?? null,
    anomalies: deriveAnomalies(c),
    rca: deriveRca(c),
    agents: deriveAgents(c),
    decisionTrace: c.decision_trace ?? [
      'Telemetry Received', 'Threshold Evaluation', 'Anomaly Detection', 'Evidence Collection',
      'Root Cause Analysis', 'Confidence Calculation', 'Human Review Recommendation', 'Report Generation',
    ],
    risk: c.risk_assessment ?? [],
    audit: deriveAudit(c),
    transparency: c.system_transparency ?? null,
    completeness: deriveCompleteness(c),
    review: deriveReview(c),
    executive: deriveExecutive(c),
    reportStatus: c.report_status ?? 'PROVISIONAL',
    classification: c.classification ?? 'CONFIDENTIAL — INTERNAL USE',
    investigationId: c.investigation_id ?? null,
    satelliteHealth: c.satellite_health ?? null,
    detectionTime: c.detection_time ?? null,
    startedAt: c.investigation_started_at ?? null,
    completedAt: c.investigation_completed_at ?? null,
  };
}
